files:
  include:
    - 'app/assets/stylesheets/**/*.scss'
    - 'app/javascript/**/*.scss'
  exclude:
    - 'node_modules/**/*'
    - 'bundle/**/*'
    - 'app/assets/stylesheets/bootstrap/**/*'
    - 'app/assets/stylesheets/vendor/**/*'
    - 'app/assets/stylesheets/gems/**/*'

linters:
  NestingDepth:
    enabled: true
    max_depth: 5
