files:
  include:
    - 'app/assets/stylesheets/**/*.scss'
    - 'app/javascript/**/*.scss'
  exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'app/assets/stylesheets/bootstrap/**/*'

linters:
  NestingDepth:
    enabled: true
    max_depth: 5
